@echo off
echo Starting Tidy Home Local Server...
echo.
echo Installing cross-env for Windows compatibility...
call npm install cross-env --save-dev
echo.
echo Starting Vite development server...
npx vite --host --open
