import React, { createContext, useContext, useState, useEffect } from 'react';
import type { Language } from '../types';

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const languages: Language[] = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español' }
];

const translations = {
  en: {
    'nav.about': 'About',
    'nav.process': 'Process',
    'nav.services': 'Services',
    'nav.contact': 'Book With Us',
    'hero.tagline': 'Your Space Matters',
    'hero.title': 'Calm, beautiful spaces that work for your life',
    'hero.subtitle': 'Transform your home with Puerto Rico\'s premier luxury organization service',
    'hero.description': 'We specialize in curated, clutter-free living, simplifying closets, kitchens, playrooms, and garages for a seamless lifestyle.',
    'hero.cta.primary': 'Book Your Consultation',
    'hero.cta.secondary': 'Discover Our Process',
    'hero.stats.number': '500+',
    'hero.stats.text': 'Homes Transformed',
    'services.title': 'Our Services',
    'services.subtitle': 'Comprehensive solutions for every space in your home',
    'services.home-organization.title': 'HOME ORGANIZATION',
    'services.home-organization.description': 'Create customized, clutter-free spaces that reflect your style.',
    'services.moving-concierge.title': 'MOVING CONCIERGE',
    'services.moving-concierge.description': 'Stress-free transitions from one home to the next.',
    'services.space-creation.title': 'SPACE CREATION',
    'services.space-creation.description': 'Transform everyday spaces into functional, beautiful environments.',
    'services.refresh-sessions.title': 'REFRESH SESSIONS',
    'services.refresh-sessions.description': 'Maintain your organized spaces with ongoing support.',
    'services.additional-services.title': 'ADDITIONAL SERVICES',
    'services.additional-services.description': 'Trusted solutions including handy work, electrical, and cleaning.',
    'services.gift-certificates.title': 'GIFT CERTIFICATES',
    'services.gift-certificates.description': 'Give the gift of a beautifully organized home.',
    'services.learn-more': 'Learn More →',
    'process.title': 'PROCESS',
    'process.subtitle': 'How We Transform Your Space',
    'process.step1.title': 'INITIAL FORM & CONSULTATION',
    'process.step1.description': '15-minute discovery call followed by in-person assessment of your space and needs.',
    'process.step2.title': 'PROJECT PROPOSAL & ONBOARDING',
    'process.step2.description': 'Customized project plan tailored to your home with guided onboarding process.',
    'process.step3.title': 'PLANNING & SHOPPING',
    'process.step3.description': 'We handle product sourcing to ensure a smooth, effortless experience.',
    'process.step4.title': 'PROJECT DAY',
    'process.step4.description': 'Transform your space with thoughtful decluttering and functional organization.',
    'process.cta': 'Contact Us',
    'about.title': 'ABOUT',
    'about.subtitle': 'The Journey',
    'about.description': 'Tidy Home began as a small, boutique home organization service with one clear goal; to help clients create calm, beautiful spaces they could truly enjoy. Over time, our passion for organization and client care led us to expand both our expertise and our reach. What started as helping organize a single room has grown into offering full-home transformations and complete lifestyle support, always with the same attention to detail and personal touch that defined us from the start.',
    'about.cta': 'Contact Us',
    'instagram.title': 'follow us on instagram',
    'instagram.handle': '@tidyhomepr',
    'instagram.follow': 'Follow @tidyhomepr',
    'contact.title': 'Get Started Today',
    'contact.phone': '(939) 202-1008',
    'contact.phone.hours': 'Monday-Friday: 8:00 AM - 6:00 PM',
    'contact.email': 'info@tidyhomepr.com',
    'contact.email.response': 'We\'ll respond within 24 hours',
    'contact.location': 'Dorado, Puerto Rico',
    'contact.location.areas': 'Serving Dorado, San Juan, Guaynabo, Bayamón',
    'contact.form.firstName': 'First Name',
    'contact.form.lastName': 'Last Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.service': 'Select Service',
    'contact.form.message': 'Tell us about your project...',
    'contact.form.submit': 'Send Message',
    'footer.tagline': 'YOUR SPACE MATTERS',
    'footer.description': 'Puerto Rico\'s premier luxury organization service, creating calm and beautiful spaces that work for your life.',
    'footer.services': 'Services',
    'footer.company': 'Company',
    'footer.contact': 'Contact',
    'footer.copyright': '© 2024 Tidy Home Puerto Rico. All rights reserved.',
    // Newsletter Popup
    'newsletter.title': 'Stay Updated',
    'newsletter.description': 'Get organizing tips, before & after transformations, and exclusive offers delivered to your inbox.',
    'newsletter.email.placeholder': 'Enter your email',
    'newsletter.button.subscribe': 'Subscribe',
    'newsletter.button.subscribing': 'Subscribing...',
    'newsletter.privacy': 'We respect your privacy. Unsubscribe at any time.',
    'newsletter.success.title': 'Success!',
    'newsletter.success.description': 'Thank you for subscribing to our newsletter.',
    'newsletter.already.title': 'Already Subscribed',
    'newsletter.already.description': "You're already subscribed to our newsletter.",
    'newsletter.error.title': 'Error',
    'newsletter.error.description': 'Failed to subscribe. Please try again.',
    // Brand Introduction
    'brand.title': 'Creating Calm, Beautiful Spaces',
    'brand.description': "At Tidy Home, we believe that an organized space is more than just aesthetic—it's about creating calm in your daily life. Our boutique organization service brings luxury, functionality, and peace to every corner of your home.",
    // Why Tidy Home
    'why.title': 'Why Tidy Home',
    'why.benefit1': 'Personalized systems tailored to your lifestyle',
    'why.benefit2': 'Full-service transformations from start to finish',
    'why.benefit3': 'Lasting solutions that are easy to maintain',
    'why.benefit4': 'Trusted by families across Puerto Rico',
    'why.cta': 'Learn More',
    // Service Modal
    'modal.home-organization.title': 'HOME ORGANIZATION',
    'modal.home-organization.description': 'We create customized, clutter-free spaces that reflect your style while promoting order and harmony.\n\nBefore the project begins, we prepare a personalized mood board and lay the groundwork to bring your vision to life.\n\nTidy Home evolves with your needs adding products or labels to maintain long-term functionality.',
    'modal.home-organization.services': 'Decluttering|Product sourcing and returns|Space planning|Installations|Donation drop-offs after each session',
    'modal.moving-concierge.title': 'MOVING CONCIERGE',
    'modal.moving-concierge.description': 'Tidy Home redefines the moving experience, delivering seamless, stress-free transitions from one home to the next.\n\nWith meticulous attention to detail, we manage every aspect of your move; planning, coordination, and execution with precision and grace.',
    'modal.moving-concierge.services': 'Packing – Decluttering, procurement of materials, and item classification|Moving Management – Day-of supervision, storage solutions, and coordination|Unpacking & Organizing – Space planning, system creation, and setup of home essentials',
    'modal.space-creation.title': 'SPACE CREATION',
    'modal.space-creation.description': 'Tidy Home transforms everyday spaces into functional, beautifully tailored environments.\n\nFrom reimagining a cluttered pantry to designing a streamlined garage, we bring thoughtful styling and practical solutions to every corner of your home.',
    'modal.space-creation.services': 'Before & After consultations|Custom storage solutions|Space optimization|Aesthetic enhancements',
    'modal.refresh-sessions.title': 'REFRESH SESSIONS',
    'modal.refresh-sessions.description': 'Life evolves, and so should your spaces. Our Refresh Sessions offer the perfect opportunity to maintain your organized home or adapt it to new needs.\n\nThese are ideal for seasonal updates, post-holiday resets, or when life changes demand a fresh approach.',
    'modal.refresh-sessions.note': 'Refresh Sessions are exclusive to returning clients and require a previously completed Tidy Home project.',
    'modal.additional-services.title': 'ADDITIONAL SERVICES',
    'modal.additional-services.description': 'Beyond organization, we connect you with trusted professionals for every home need.\n\nOur vetted network ensures quality service for:',
    'modal.additional-services.services': 'Handywork & minor repairs|Electrical services|Deep cleaning|Furniture assembly|Custom installations',
    'modal.gift-certificates.title': 'GIFT CERTIFICATES',
    'modal.gift-certificates.description': 'Give the gift of calm and order. Our gift certificates offer a thoughtful way to help someone special transform their space and simplify their life.\n\nPerfect for housewarmings, new parents, or anyone ready for a fresh start.',
    'modal.gift-certificates.cta': 'Purchase a Gift Certificate',
    'modal.close': 'Close',
    // Connect Page
    'connect.title': 'Connect With Us',
    'connect.description': "Ready to transform your space? Choose the service that best fits your needs and let's begin your journey to a beautifully organized home.",
    'connect.form.first-time.title': 'First Time Project',
    'connect.form.first-time.description': 'Starting fresh with Tidy Home? This comprehensive service covers everything from initial consultation to complete transformation.',
    'connect.form.spanish.title': 'PROYECTO INICIAL',
    'connect.form.spanish.description': 'For our Spanish-speaking clients who prefer to communicate in their native language throughout the entire process.',
    'connect.form.moving.title': 'Moving Services',
    'connect.form.moving.description': "Moving doesn't have to feel overwhelming. Our concierge service handles every detail of your transition with care and precision.",
    'connect.form.refresh.title': 'Refresh Sessions',
    'connect.form.refresh.description': 'For existing clients looking to maintain and refresh their organized spaces with ongoing support.',
    // Contact/FAQ Page
    'contact.page.title': 'Contact Us',
    'contact.page.subtitle': 'Transform your space today',
    'contact.form.title': 'Send us a message',
    'contact.form.name': 'Name',
    'contact.form.question': 'Your question or message',
    'contact.form.submitting': 'Sending...',
    'contact.success.title': 'Message Sent!',
    'contact.success.description': 'Thank you for contacting us. We will respond within 24 hours.',
    'contact.error.title': 'Error',
    'contact.error.description': 'Failed to send message. Please try again or contact us directly.',
    'contact.faqs.title': 'Frequently Asked Questions',
    'contact.faq1.question': 'WHAT SERVICES DO YOU OFFER?',
    'contact.faq1.answer': 'We offer comprehensive home organization services including home organization, moving concierge, space creation, refresh sessions, additional services, and gift certificates. Each service is tailored to meet your specific needs and lifestyle.',
    'contact.faq2.question': 'HOW FAR IN ADVANCE SHOULD I BOOK?',
    'contact.faq2.answer': 'We recommend booking 2-4 weeks in advance to ensure availability, especially during peak seasons. However, we do our best to accommodate urgent requests when possible.',
    'contact.faq3.question': 'HOW DO YOU CHARGE FOR YOUR SERVICES?',
    'contact.faq3.answer': 'Our pricing is customized based on the scope of your project, space size, and specific requirements. After our initial consultation, we provide a detailed proposal with transparent pricing.',
    'contact.faq4.question': 'HOW DO I GET STARTED?',
    'contact.faq4.answer': 'Simply visit our Connect With Us page and choose the service that best fits your needs. Fill out the form, and we will schedule your consultation to discuss your project in detail.',
    'contact.faq5.question': 'WHAT AREAS DO YOU SERVE?',
    'contact.faq5.answer': 'We proudly serve all areas across Puerto Rico. Travel fees may apply for locations outside the metro area, which will be discussed during consultation.',
    // Header Navigation
    'header.schedule_consultation': 'Schedule a Free Consultation',
    'nav.home': 'HOME',
    'nav.connect': 'CONNECT WITH US',
    'nav.portfolio': 'PORTFOLIO',
    'nav.faqs': 'FAQS',
    // Hero Section Additional
    'hero.main_title': 'YOUR SPACE MATTERS',
    'hero.company_name': 'The Tidy Touch',
    'hero.cta.book_consultation': 'Book Your Consultation',
    'hero.cta.discover_process': 'Discover Our Process',
    // Process Section
    'process.step_1_title': 'CONSULTATION',
    'process.step_1_description': 'We meet with you to understand your unique needs and vision.',
    'process.step_2_title': 'PLANNING',
    'process.step_2_description': 'We create a personalized organization strategy for your home.',
    'process.step_3_title': 'SHOPPING',
    'process.step_3_description': 'We source the perfect products to bring your plan to life.',
    'process.step_4_title': 'TRANSFORMATION',
    'process.step_4_description': 'We implement beautiful, functional systems that last.',
    'process.cta_button': 'Get Started Today',
    // Contact Form
    'contact.form.full_name': 'Full Name *',
    'contact.form.email_label': 'Email *',
    'contact.form.phone_label': 'Phone Number *',
    'contact.form.question_label': 'Your Question *',
    'contact.form.question_placeholder': 'Please share your question here...',
    'contact.form.send_button': 'Send Question',
    'contact.form.sending': 'Sending...',
    'contact.looking_to_start': 'Looking to Get Started?',
    'contact.looking_description': 'Ready to transform your space? Our team is here to guide you through every step of creating the organized, beautiful home you\'ve always wanted.',
    'contact.still_questions': 'Still Have Questions?',
    'contact.still_description': 'We understand that organizing your home is a personal journey. Feel free to reach out with any questions about our services, process, or how we can help transform your space.',
    // Portfolio
    'portfolio.title': 'Our Portfolio',
    'portfolio.subtitle': 'Explore our transformations and see how we bring calm and order to every space.',
    'portfolio.categories.all': 'All Projects',
    'portfolio.categories.organization': 'Organization',
    'portfolio.categories.space_creation': 'Space Creation',
    'portfolio.categories.moving': 'Moving Services',
    // Portfolio Items
    'portfolio.item1.title': 'Modern Kitchen Organization',
    'portfolio.item2.title': 'Luxury Closet System',
    'portfolio.item3.title': 'Home Office Transformation',
    'portfolio.item4.title': 'Pantry Organization',
    'portfolio.item5.title': 'Garage Organization',
    'portfolio.item6.title': 'Playroom Organization',
    // Footer Additional
    'footer.contact_info': 'Contact Info',
    'footer.email': 'info@tidyhomepr.com',
    'footer.hours': 'Mon-Fri: 9AM - 5PM',
    'footer.service_areas': 'Serving Dorado, San Juan, Guaynabo & Bayamón',
    'footer.home_organization': 'Home Organization',
    'footer.moving_concierge': 'Moving Concierge',
    'footer.space_creation': 'Space Creation',
    'footer.refresh_sessions': 'Refresh Sessions',
    'footer.about_link': 'About',
    'footer.services_link': 'Services',
    'footer.portfolio_link': 'Portfolio',
    'footer.faqs_link': 'FAQs',
    // ServiceGrid
    'services.grid_subtitle': 'Explore our comprehensive organization and lifestyle support services',
    'services.get_started': 'Get Started',
    'services.view_faqs': 'View FAQs',
    // Connect Page Additional
    'connect.not_sure': 'Not sure which service is right for you?',
    'connect.contact_note': 'Contact form will be integrated here with HoneyBook',
    // Connect Form Features
    'connect.form.first-time.feature1': 'Complete home assessment',
    'connect.form.first-time.feature2': 'Custom organization systems',
    'connect.form.first-time.feature3': 'Product sourcing included',
    'connect.form.first-time.feature4': 'Team implementation',
    'connect.form.moving.feature1': 'Pre-move decluttering',
    'connect.form.moving.feature2': 'Professional packing',
    'connect.form.moving.feature3': 'New home setup',
    'connect.form.moving.feature4': 'Unpacking & organizing',
    'connect.form.refresh.feature1': 'System maintenance',
    'connect.form.refresh.feature2': 'Seasonal updates',
    'connect.form.refresh.feature3': 'Quick reorganization',
    'connect.form.refresh.feature4': 'Ongoing support',
    'connect.form.spanish.feature1': 'Complete assessment',
    'connect.form.spanish.feature2': 'Custom systems',
    'connect.form.spanish.feature3': 'Products included',
    'connect.form.spanish.feature4': 'Professional implementation',
    // WhatsApp
    'whatsapp.aria_label': 'Contact us on WhatsApp',
    // About Page
    'about.page.title': 'About Tidy Home',
    'about.brand.title': 'Our Brand',
    'about.brand.paragraph1': 'At Tidy Home, we believe that your space matters. More than just organizing, we create sanctuaries that reflect your lifestyle and bring calm to your daily life. Our approach combines luxury with functionality, ensuring every system we implement is both beautiful and sustainable.',
    'about.brand.paragraph2': 'Founded in Puerto Rico, we\'ve transformed over 500 homes across the island, working with families, busy professionals, and individuals who understand the value of an organized life. Our white-glove service means we handle every detail with discretion and care, creating spaces that work as beautifully as they look.',
    'about.journey.title': 'The Journey',
    'about.journey.paragraph1': 'Our journey began with a simple belief: everyone deserves a space that supports their best life. What started as a passion for organization has grown into Puerto Rico\'s premier luxury home organization service.',
    'about.journey.paragraph2': 'Over the years, we\'ve refined our process, expanded our team, and deepened our commitment to excellence. Today, we\'re proud to offer comprehensive solutions that go beyond traditional organizing – from complete home transformations to moving concierge services and ongoing maintenance support.',
    'about.journey.paragraph3': 'Our success is measured not just in the spaces we transform, but in the lives we touch. When clients tell us they feel lighter, more productive, or simply happier in their homes, we know we\'ve fulfilled our mission.',
    'about.team.title': 'Meet Valeria & Raul',
    'about.team.description': 'Valeria and Raul, a husband-and-wife team, founded Tidy Home with a shared vision of creating spaces that feel curated and intentional. Valeria, an interior stylist with a love for organization and space creation, brings ideas and designs to life through thoughtful details and creative projects. Raul is the hands-on force behind the vision, painting, installing, and problem-solving with skill and versatility. Together, they balance creativity and craftsmanship, leading a team that can take on any project and transform any space into a reflection of your lifestyle and vision.',
    // Services Page
    'services.page.title': 'Our Services',
    'services.page.subtitle': 'Comprehensive solutions designed to transform your space and simplify your life',
    // FAQs Page
    'faqs.page.title': 'Looking to Get Started?',
    'faqs.page.subtitle': 'Find answers to common questions about our services',
    'faqs.faq1.question': 'How far in advance should I book?',
    'faqs.faq1.answer': 'We recommend booking at least 2-3 weeks in advance to ensure availability. Peak season runs September through March, so during these months, we suggest booking 4-6 weeks ahead for the best scheduling options.',
    'faqs.faq2.question': 'How do you charge for your services?',
    'faqs.faq2.answer': 'We begin by preparing an initial estimate based on the information you share through our project request form. After our consultation, where we learn more about your space, needs, and scope, we refine the details and provide a customized proposal with transparent pricing.',
    'faqs.faq3.question': 'How do I get started?',
    'faqs.faq3.answer': 'Simply visit our Connect With Us page and choose the service that best fits your needs. Once you submit your request, you\'ll be able to schedule your consultation so we can discuss your project in more detail.',
    'faqs.faq4.question': 'What areas do you serve?',
    'faqs.faq4.answer': 'We proudly serve Dorado, San Juan, Carolina, and Bayamón with no additional travel fees. Projects outside these areas are also welcome, with travel costs discussed during your consultation.',
    'faqs.faq5.question': 'Do you provide the organizing products?',
    'faqs.faq5.answer': 'Yes! We handle all product sourcing as part of our service. During the planning phase, we create a customized product list based on your space and budget, and we take care of all the shopping for you.',
    'faqs.faq6.question': 'How long does a typical project take?',
    'faqs.faq6.answer': 'Project timelines vary based on scope. A single room organization typically takes 6-8 hours, while whole-home projects may span multiple days. We provide a detailed timeline in your project proposal.',
    'faqs.faq7.question': 'Do I need to be present during the project?',
    'faqs.faq7.answer': 'While we love working alongside our clients, it\'s not required. Many clients prefer to return to a fully transformed space. We\'ll discuss your preference during the consultation.',
    'faqs.faq8.question': 'What happens to items I no longer want?',
    'faqs.faq8.answer': 'We can coordinate donation pickups, arrange for recycling, or disposal as needed. We work with local charities and ensure items are handled responsibly.',
    'faqs.still_questions': 'Still have questions?',
    'faqs.still_questions_text': 'For any additional questions, complete the form below and a member of our team will be in touch with you shortly.',
    'faqs.form.name': 'Your Name',
    'faqs.form.email': 'Email Address',
    'faqs.form.question': 'Your Question',
    'faqs.form.send': 'Send Question',
  },
  es: {
    'nav.about': 'Acerca de',
    'nav.process': 'Proceso',
    'nav.services': 'Servicios',
    'nav.contact': 'Reserva Con Nosotros',
    'hero.tagline': 'Tu Espacio Importa',
    'hero.title': 'Espacios serenos y hermosos que funcionan para tu vida',
    'hero.subtitle': 'Transforma tu hogar con el servicio de organización de lujo premier de Puerto Rico',
    'hero.description': 'Nos especializamos en una vida curada y libre de desorden, simplificando armarios, cocinas, salas de juego y garajes para un estilo de vida perfecto.',
    'hero.cta.primary': 'Reserva Tu Consulta',
    'hero.cta.secondary': 'Descubre Nuestro Proceso',
    'hero.stats.number': '500+',
    'hero.stats.text': 'Hogares Transformados',
    'services.title': 'Nuestros Servicios',
    'services.subtitle': 'Soluciones integrales para cada espacio de tu hogar',
    'services.home-organization.title': 'ORGANIZACIÓN DEL HOGAR',
    'services.home-organization.description': 'Crea espacios personalizados y libres de desorden que reflejen tu estilo.',
    'services.moving-concierge.title': 'SERVICIO DE MUDANZA',
    'services.moving-concierge.description': 'Transiciones sin estrés de un hogar al siguiente.',
    'services.space-creation.title': 'CREACIÓN DE ESPACIOS',
    'services.space-creation.description': 'Transforma espacios cotidianos en ambientes funcionales y hermosos.',
    'services.refresh-sessions.title': 'SESIONES DE RENOVACIÓN',
    'services.refresh-sessions.description': 'Mantén tus espacios organizados con apoyo continuo.',
    'services.additional-services.title': 'SERVICIOS ADICIONALES',
    'services.additional-services.description': 'Soluciones confiables incluyendo trabajos manuales, eléctricos y limpieza.',
    'services.gift-certificates.title': 'CERTIFICADOS DE REGALO',
    'services.gift-certificates.description': 'Regala el obsequio de un hogar hermosamente organizado.',
    'services.learn-more': 'Saber Más →',
    'process.title': 'PROCESO',
    'process.subtitle': 'Cómo Transformamos Tu Espacio',
    'process.step1.title': 'FORMULARIO INICIAL Y CONSULTA',
    'process.step1.description': 'Llamada de descubrimiento de 15 minutos seguida de evaluación en persona de tu espacio y necesidades.',
    'process.step2.title': 'PROPUESTA DE PROYECTO E INCORPORACIÓN',
    'process.step2.description': 'Plan de proyecto personalizado adaptado a tu hogar con proceso de incorporación guiado.',
    'process.step3.title': 'PLANIFICACIÓN Y COMPRAS',
    'process.step3.description': 'Manejamos la búsqueda de productos para asegurar una experiencia suave y sin esfuerzo.',
    'process.step4.title': 'DÍA DEL PROYECTO',
    'process.step4.description': 'Transforma tu espacio con desorden reflexivo y organización funcional.',
    'process.cta': 'Contáctanos',
    'about.title': 'ACERCA DE',
    'about.subtitle': 'El Viaje',
    'about.description': 'Tidy Home comenzó como un pequeño servicio boutique de organización del hogar con un objetivo claro; ayudar a los clientes a crear espacios serenos y hermosos que realmente pudieran disfrutar. Con el tiempo, nuestra pasión por la organización y el cuidado del cliente nos llevó a expandir tanto nuestra experiencia como nuestro alcance. Lo que comenzó como ayudar a organizar una sola habitación ha crecido hasta ofrecer transformaciones completas del hogar y apoyo completo del estilo de vida, siempre con la misma atención al detalle y toque personal que nos definió desde el principio.',
    'about.cta': 'Contáctanos',
    'instagram.title': 'síguenos en instagram',
    'instagram.handle': '@tidyhomepr',
    'instagram.follow': 'Seguir @tidyhomepr',
    'contact.title': 'Comienza Hoy',
    'contact.phone': '(939) 202-1008',
    'contact.phone.hours': 'Lunes-Viernes: 8:00 AM - 6:00 PM',
    'contact.email': 'info@tidyhomepr.com',
    'contact.email.response': 'Responderemos dentro de 24 horas',
    'contact.location': 'Dorado, Puerto Rico',
    'contact.location.areas': 'Sirviendo Dorado, San Juan, Guaynabo, Bayamón',
    'contact.form.firstName': 'Nombre',
    'contact.form.lastName': 'Apellido',
    'contact.form.email': 'Correo Electrónico',
    'contact.form.phone': 'Número de Teléfono',
    'contact.form.service': 'Seleccionar Servicio',
    'contact.form.message': 'Cuéntanos sobre tu proyecto...',
    'contact.form.submit': 'Enviar Mensaje',
    'footer.tagline': 'TU ESPACIO IMPORTA',
    'footer.description': 'El servicio de organización de lujo premier de Puerto Rico, creando espacios serenos y hermosos que funcionan para tu vida.',
    'footer.services': 'Servicios',
    'footer.company': 'Empresa',
    'footer.contact': 'Contacto',
    'footer.copyright': '© 2024 Tidy Home Puerto Rico. Todos los derechos reservados.',
    // Newsletter Popup
    'newsletter.title': 'Mantente Actualizado',
    'newsletter.description': 'Recibe consejos de organización, transformaciones de antes y después, y ofertas exclusivas directamente en tu correo.',
    'newsletter.email.placeholder': 'Ingresa tu correo electrónico',
    'newsletter.button.subscribe': 'Suscribirse',
    'newsletter.button.subscribing': 'Suscribiendo...',
    'newsletter.privacy': 'Respetamos tu privacidad. Cancela tu suscripción en cualquier momento.',
    'newsletter.success.title': '¡Éxito!',
    'newsletter.success.description': 'Gracias por suscribirte a nuestro boletín.',
    'newsletter.already.title': 'Ya Suscrito',
    'newsletter.already.description': 'Ya estás suscrito a nuestro boletín.',
    'newsletter.error.title': 'Error',
    'newsletter.error.description': 'No se pudo suscribir. Por favor intenta de nuevo.',
    // Brand Introduction
    'brand.title': 'Creando Espacios Serenos y Hermosos',
    'brand.description': 'En Tidy Home, creemos que un espacio organizado es más que estética—se trata de crear calma en tu vida diaria. Nuestro servicio boutique de organización trae lujo, funcionalidad y paz a cada rincón de tu hogar.',
    // Why Tidy Home
    'why.title': 'Por Qué Tidy Home',
    'why.benefit1': 'Sistemas personalizados adaptados a tu estilo de vida',
    'why.benefit2': 'Transformaciones completas de principio a fin',
    'why.benefit3': 'Soluciones duraderas y fáciles de mantener',
    'why.benefit4': 'Confianza de familias en todo Puerto Rico',
    'why.cta': 'Aprende Más',
    // Service Modal
    'modal.home-organization.title': 'ORGANIZACIÓN DEL HOGAR',
    'modal.home-organization.description': 'Creamos espacios personalizados y libres de desorden que reflejan tu estilo mientras promueven el orden y la armonía.\n\nAntes de que comience el proyecto, preparamos un tablero de inspiración personalizado y sentamos las bases para dar vida a tu visión.\n\nTidy Home evoluciona con tus necesidades agregando productos o etiquetas para mantener la funcionalidad a largo plazo.',
    'modal.home-organization.services': 'Desorden|Búsqueda de productos y devoluciones|Planificación del espacio|Instalaciones|Entrega de donaciones después de cada sesión',
    'modal.moving-concierge.title': 'SERVICIO DE MUDANZA',
    'modal.moving-concierge.description': 'Tidy Home redefine la experiencia de mudanza, brindando transiciones perfectas y sin estrés de un hogar al siguiente.\n\nCon meticulosa atención al detalle, manejamos cada aspecto de tu mudanza; planificación, coordinación y ejecución con precisión y gracia.',
    'modal.moving-concierge.services': 'Empaque – Desorden, adquisición de materiales y clasificación de artículos|Gestión de Mudanza – Supervisión del día, soluciones de almacenamiento y coordinación|Desempaque y Organización – Planificación del espacio, creación de sistemas y configuración de elementos esenciales del hogar',
    'modal.space-creation.title': 'CREACIÓN DE ESPACIOS',
    'modal.space-creation.description': 'Tidy Home transforma espacios cotidianos en ambientes funcionales y bellamente adaptados.\n\nDesde reimaginar una despensa desordenada hasta diseñar un garaje optimizado, aportamos estilo reflexivo y soluciones prácticas a cada rincón de tu hogar.',
    'modal.space-creation.services': 'Consultas de antes y después|Soluciones de almacenamiento personalizadas|Optimización del espacio|Mejoras estéticas',
    'modal.refresh-sessions.title': 'SESIONES DE RENOVACIÓN',
    'modal.refresh-sessions.description': 'La vida evoluciona, y tus espacios también deberían hacerlo. Nuestras Sesiones de Renovación ofrecen la oportunidad perfecta para mantener tu hogar organizado o adaptarlo a nuevas necesidades.\n\nSon ideales para actualizaciones estacionales, reinicios después de las fiestas, o cuando los cambios de vida exigen un enfoque fresco.',
    'modal.refresh-sessions.note': 'Las Sesiones de Renovación son exclusivas para clientes que regresan y requieren un proyecto de Tidy Home completado previamente.',
    'modal.additional-services.title': 'SERVICIOS ADICIONALES',
    'modal.additional-services.description': 'Más allá de la organización, te conectamos con profesionales de confianza para cada necesidad del hogar.\n\nNuestra red verificada garantiza servicio de calidad para:',
    'modal.additional-services.services': 'Trabajos manuales y reparaciones menores|Servicios eléctricos|Limpieza profunda|Ensamblaje de muebles|Instalaciones personalizadas',
    'modal.gift-certificates.title': 'CERTIFICADOS DE REGALO',
    'modal.gift-certificates.description': 'Regala calma y orden. Nuestros certificados de regalo ofrecen una forma considerada de ayudar a alguien especial a transformar su espacio y simplificar su vida.\n\nPerfecto para inauguraciones de casa, nuevos padres, o cualquiera listo para un nuevo comienzo.',
    'modal.gift-certificates.cta': 'Comprar un Certificado de Regalo',
    'modal.close': 'Cerrar',
    // Connect Page
    'connect.title': 'Conéctate Con Nosotros',
    'connect.description': '¿Listo para transformar tu espacio? Elige el servicio que mejor se adapte a tus necesidades y comencemos tu viaje hacia un hogar hermosamente organizado.',
    'connect.form.first-time.title': 'Proyecto Inicial',
    'connect.form.first-time.description': '¿Comenzando de nuevo con Tidy Home? Este servicio integral cubre todo, desde la consulta inicial hasta la transformación completa.',
    'connect.form.spanish.title': 'PROYECTO INICIAL',
    'connect.form.spanish.description': 'Para nuestros clientes de habla hispana que prefieren comunicarse en su idioma nativo durante todo el proceso.',
    'connect.form.moving.title': 'Servicios de Mudanza',
    'connect.form.moving.description': 'Mudarse no tiene que sentirse abrumador. Nuestro servicio de conserjería maneja cada detalle de tu transición con cuidado y precisión.',
    'connect.form.refresh.title': 'Sesiones de Renovación',
    'connect.form.refresh.description': 'Para clientes existentes que buscan mantener y renovar sus espacios organizados con apoyo continuo.',
    // Contact/FAQ Page
    'contact.page.title': 'Contáctanos',
    'contact.page.subtitle': 'Transforma tu espacio hoy',
    'contact.form.title': 'Envíanos un mensaje',
    'contact.form.name': 'Nombre',
    'contact.form.question': 'Tu pregunta o mensaje',
    'contact.form.submitting': 'Enviando...',
    'contact.success.title': '¡Mensaje Enviado!',
    'contact.success.description': 'Gracias por contactarnos. Responderemos dentro de 24 horas.',
    'contact.error.title': 'Error',
    'contact.error.description': 'No se pudo enviar el mensaje. Por favor intenta de nuevo o contáctanos directamente.',
    'contact.faqs.title': 'Preguntas Frecuentes',
    'contact.faq1.question': '¿QUÉ SERVICIOS OFRECEN?',
    'contact.faq1.answer': 'Ofrecemos servicios integrales de organización del hogar que incluyen organización del hogar, servicio de mudanza, creación de espacios, sesiones de renovación, servicios adicionales y certificados de regalo. Cada servicio está adaptado para satisfacer tus necesidades y estilo de vida específicos.',
    'contact.faq2.question': '¿CON CUÁNTA ANTICIPACIÓN DEBO RESERVAR?',
    'contact.faq2.answer': 'Recomendamos reservar con 2-4 semanas de anticipación para garantizar disponibilidad, especialmente durante las temporadas altas. Sin embargo, hacemos nuestro mejor esfuerzo para acomodar solicitudes urgentes cuando es posible.',
    'contact.faq3.question': '¿CÓMO COBRAN POR SUS SERVICIOS?',
    'contact.faq3.answer': 'Nuestros precios se personalizan según el alcance de tu proyecto, el tamaño del espacio y los requisitos específicos. Después de nuestra consulta inicial, proporcionamos una propuesta detallada con precios transparentes.',
    'contact.faq4.question': '¿CÓMO EMPIEZO?',
    'contact.faq4.answer': 'Simplemente visita nuestra página Conéctate Con Nosotros y elige el servicio que mejor se adapte a tus necesidades. Llena el formulario y programaremos tu consulta para discutir tu proyecto en detalle.',
    'contact.faq5.question': '¿QUÉ ÁREAS ATIENDEN?',
    'contact.faq5.answer': 'Orgullosamente servimos todas las áreas de Puerto Rico. Pueden aplicar tarifas de viaje para ubicaciones fuera del área metropolitana, lo cual se discutirá durante la consulta.',
    // Header Navigation
    'header.schedule_consultation': 'Agenda una Consulta Gratuita',
    'nav.home': 'INICIO',
    'nav.connect': 'CONÉCTATE CON NOSOTROS',
    'nav.portfolio': 'PORTAFOLIO',
    'nav.faqs': 'PREGUNTAS FRECUENTES',
    // Hero Section Additional
    'hero.main_title': 'TU ESPACIO IMPORTA',
    'hero.company_name': 'El Toque Organizado',
    'hero.cta.book_consultation': 'Reserva Tu Consulta',
    'hero.cta.discover_process': 'Descubre Nuestro Proceso',
    // Process Section
    'process.step_1_title': 'CONSULTA',
    'process.step_1_description': 'Nos reunimos contigo para entender tus necesidades y visión únicas.',
    'process.step_2_title': 'PLANIFICACIÓN',
    'process.step_2_description': 'Creamos una estrategia de organización personalizada para tu hogar.',
    'process.step_3_title': 'COMPRAS',
    'process.step_3_description': 'Conseguimos los productos perfectos para dar vida a tu plan.',
    'process.step_4_title': 'TRANSFORMACIÓN',
    'process.step_4_description': 'Implementamos sistemas hermosos y funcionales que perduran.',
    'process.cta_button': 'Comienza Hoy',
    // Contact Form
    'contact.form.full_name': 'Nombre Completo *',
    'contact.form.email_label': 'Correo Electrónico *',
    'contact.form.phone_label': 'Número de Teléfono *',
    'contact.form.question_label': 'Tu Pregunta *',
    'contact.form.question_placeholder': 'Por favor comparte tu pregunta aquí...',
    'contact.form.send_button': 'Enviar Pregunta',
    'contact.form.sending': 'Enviando...',
    'contact.looking_to_start': '¿Listo para Comenzar?',
    'contact.looking_description': '¿Listo para transformar tu espacio? Nuestro equipo está aquí para guiarte en cada paso de crear el hogar organizado y hermoso que siempre has querido.',
    'contact.still_questions': '¿Aún Tienes Preguntas?',
    'contact.still_description': 'Entendemos que organizar tu hogar es un viaje personal. No dudes en contactarnos con cualquier pregunta sobre nuestros servicios, proceso, o cómo podemos ayudar a transformar tu espacio.',
    // Portfolio
    'portfolio.title': 'Nuestro Portafolio',
    'portfolio.subtitle': 'Explora nuestras transformaciones y ve cómo traemos calma y orden a cada espacio.',
    'portfolio.categories.all': 'Todos los Proyectos',
    'portfolio.categories.organization': 'Organización',
    'portfolio.categories.space_creation': 'Creación de Espacios',
    'portfolio.categories.moving': 'Servicios de Mudanza',
    // Portfolio Items
    'portfolio.item1.title': 'Organización de Cocina Moderna',
    'portfolio.item2.title': 'Sistema de Closet de Lujo',
    'portfolio.item3.title': 'Transformación de Oficina en Casa',
    'portfolio.item4.title': 'Organización de Despensa',
    'portfolio.item5.title': 'Organización de Garaje',
    'portfolio.item6.title': 'Organización de Cuarto de Juegos',
    // Footer Additional
    'footer.contact_info': 'Información de Contacto',
    'footer.email': 'info@tidyhomepr.com',
    'footer.hours': 'Lun-Vie: 9AM - 5PM',
    'footer.service_areas': 'Sirviendo Dorado, San Juan, Guaynabo y Bayamón',
    'footer.home_organization': 'Organización del Hogar',
    'footer.moving_concierge': 'Servicio de Mudanza',
    'footer.space_creation': 'Creación de Espacios',
    'footer.refresh_sessions': 'Sesiones de Renovación',
    'footer.about_link': 'Acerca de',
    'footer.services_link': 'Servicios',
    'footer.portfolio_link': 'Portafolio',
    'footer.faqs_link': 'Preguntas Frecuentes',
    // ServiceGrid
    'services.grid_subtitle': 'Explore nuestros servicios integrales de organización y soporte de estilo de vida',
    'services.get_started': 'Comenzar',
    'services.view_faqs': 'Ver Preguntas Frecuentes',
    // Connect Page Additional
    'connect.not_sure': '¿No estás seguro qué servicio es el correcto para ti?',
    'connect.contact_note': 'El formulario de contacto se integrará aquí con HoneyBook',
    // Connect Form Features
    'connect.form.first-time.feature1': 'Evaluación completa del hogar',
    'connect.form.first-time.feature2': 'Sistemas de organización personalizados',
    'connect.form.first-time.feature3': 'Búsqueda de productos incluida',
    'connect.form.first-time.feature4': 'Implementación del equipo',
    'connect.form.moving.feature1': 'Desorden previo a la mudanza',
    'connect.form.moving.feature2': 'Empaque profesional',
    'connect.form.moving.feature3': 'Configuración del nuevo hogar',
    'connect.form.moving.feature4': 'Desempaque y organización',
    'connect.form.refresh.feature1': 'Mantenimiento del sistema',
    'connect.form.refresh.feature2': 'Actualizaciones estacionales',
    'connect.form.refresh.feature3': 'Reorganización rápida',
    'connect.form.refresh.feature4': 'Apoyo continuo',
    'connect.form.spanish.feature1': 'Evaluación completa',
    'connect.form.spanish.feature2': 'Sistemas personalizados',
    'connect.form.spanish.feature3': 'Productos incluidos',
    'connect.form.spanish.feature4': 'Implementación profesional',
    // WhatsApp
    'whatsapp.aria_label': 'Contáctanos por WhatsApp',
    // About Page
    'about.page.title': 'Acerca de Tidy Home',
    'about.brand.title': 'Nuestra Marca',
    'about.brand.paragraph1': 'En Tidy Home, creemos que tu espacio importa. Más que solo organizar, creamos santuarios que reflejan tu estilo de vida y traen calma a tu vida diaria. Nuestro enfoque combina lujo con funcionalidad, asegurando que cada sistema que implementamos sea hermoso y sostenible.',
    'about.brand.paragraph2': 'Fundado en Puerto Rico, hemos transformado más de 500 hogares en toda la isla, trabajando con familias, profesionales ocupados e individuos que entienden el valor de una vida organizada. Nuestro servicio de guante blanco significa que manejamos cada detalle con discreción y cuidado, creando espacios que funcionan tan hermosamente como lucen.',
    'about.journey.title': 'El Viaje',
    'about.journey.paragraph1': 'Nuestro viaje comenzó con una simple creencia: todos merecen un espacio que apoye su mejor vida. Lo que comenzó como una pasión por la organización ha crecido hasta convertirse en el servicio de organización de lujo premier de Puerto Rico.',
    'about.journey.paragraph2': 'A lo largo de los años, hemos refinado nuestro proceso, expandido nuestro equipo y profundizado nuestro compromiso con la excelencia. Hoy, estamos orgullosos de ofrecer soluciones integrales que van más allá de la organización tradicional: desde transformaciones completas del hogar hasta servicios de mudanza y soporte de mantenimiento continuo.',
    'about.journey.paragraph3': 'Nuestro éxito se mide no solo en los espacios que transformamos, sino en las vidas que tocamos. Cuando los clientes nos dicen que se sienten más ligeros, más productivos o simplemente más felices en sus hogares, sabemos que hemos cumplido nuestra misión.',
    'about.team.title': 'Conoce a Valeria y Raúl',
    'about.team.description': 'Valeria y Raúl, un equipo de esposo y esposa, fundaron Tidy Home con una visión compartida de crear espacios que se sientan curados e intencionales. Valeria, una estilista de interiores con amor por la organización y la creación de espacios, da vida a ideas y diseños a través de detalles reflexivos y proyectos creativos. Raúl es la fuerza práctica detrás de la visión, pintando, instalando y resolviendo problemas con habilidad y versatilidad. Juntos, equilibran creatividad y artesanía, liderando un equipo que puede asumir cualquier proyecto y transformar cualquier espacio en un reflejo de tu estilo de vida y visión.',
    // Services Page
    'services.page.title': 'Nuestros Servicios',
    'services.page.subtitle': 'Soluciones integrales diseñadas para transformar tu espacio y simplificar tu vida',
    // FAQs Page
    'faqs.page.title': '¿Listo para Comenzar?',
    'faqs.page.subtitle': 'Encuentra respuestas a preguntas comunes sobre nuestros servicios',
    'faqs.faq1.question': '¿Con cuánta anticipación debo reservar?',
    'faqs.faq1.answer': 'Recomendamos reservar con al menos 2-3 semanas de anticipación para garantizar disponibilidad. La temporada alta es de septiembre a marzo, por lo que durante estos meses sugerimos reservar con 4-6 semanas de anticipación para las mejores opciones de horario.',
    'faqs.faq2.question': '¿Cómo cobran por sus servicios?',
    'faqs.faq2.answer': 'Comenzamos preparando un estimado inicial basado en la información que compartes a través de nuestro formulario de solicitud de proyecto. Después de nuestra consulta, donde aprendemos más sobre tu espacio, necesidades y alcance, refinamos los detalles y proporcionamos una propuesta personalizada con precios transparentes.',
    'faqs.faq3.question': '¿Cómo empiezo?',
    'faqs.faq3.answer': 'Simplemente visita nuestra página Conéctate Con Nosotros y elige el servicio que mejor se adapte a tus necesidades. Una vez que envíes tu solicitud, podrás programar tu consulta para que podamos discutir tu proyecto en más detalle.',
    'faqs.faq4.question': '¿Qué áreas atienden?',
    'faqs.faq4.answer': 'Orgullosamente servimos Dorado, San Juan, Carolina y Bayamón sin tarifas adicionales de viaje. Los proyectos fuera de estas áreas también son bienvenidos, con costos de viaje discutidos durante tu consulta.',
    'faqs.faq5.question': '¿Proporcionan los productos de organización?',
    'faqs.faq5.answer': '¡Sí! Manejamos toda la búsqueda de productos como parte de nuestro servicio. Durante la fase de planificación, creamos una lista de productos personalizada basada en tu espacio y presupuesto, y nos encargamos de todas las compras por ti.',
    'faqs.faq6.question': '¿Cuánto tiempo toma un proyecto típico?',
    'faqs.faq6.answer': 'Los tiempos del proyecto varían según el alcance. La organización de una sola habitación generalmente toma de 6 a 8 horas, mientras que los proyectos de toda la casa pueden extenderse por varios días. Proporcionamos un cronograma detallado en tu propuesta de proyecto.',
    'faqs.faq7.question': '¿Necesito estar presente durante el proyecto?',
    'faqs.faq7.answer': 'Aunque nos encanta trabajar junto a nuestros clientes, no es requerido. Muchos clientes prefieren regresar a un espacio completamente transformado. Discutiremos tu preferencia durante la consulta.',
    'faqs.faq8.question': '¿Qué pasa con los artículos que ya no quiero?',
    'faqs.faq8.answer': 'Podemos coordinar recogidas de donaciones, organizar el reciclaje o la eliminación según sea necesario. Trabajamos con organizaciones benéficas locales y nos aseguramos de que los artículos se manejen de manera responsable.',
    'faqs.still_questions': '¿Aún tienes preguntas?',
    'faqs.still_questions_text': 'Para cualquier pregunta adicional, completa el formulario a continuación y un miembro de nuestro equipo se pondrá en contacto contigo pronto.',
    'faqs.form.name': 'Tu Nombre',
    'faqs.form.email': 'Correo Electrónico',
    'faqs.form.question': 'Tu Pregunta',
    'faqs.form.send': 'Enviar Pregunta',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(languages[0]);

  useEffect(() => {
    const savedLanguage = localStorage.getItem('tidyhome-language');
    if (savedLanguage) {
      const lang = languages.find(l => l.code === savedLanguage);
      if (lang) {
        setCurrentLanguage(lang);
      }
    }
  }, []);

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
    localStorage.setItem('tidyhome-language', language.code);
  };

  const t = (key: string): string => {
    // First try direct key lookup (for flat keys with dots)
    const currentTranslations = translations[currentLanguage.code as keyof typeof translations];
    const directValue = (currentTranslations as any)[key];
    if (directValue) {
      return directValue;
    }

    // If not found, try nested object access (for backwards compatibility)
    const keys = key.split('.');
    let value: any = currentTranslations;

    for (const k of keys) {
      value = value?.[k];
    }

    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export { languages };
